### ISSUE TITLE
Question: How can i open device settings on iOS?

### ISSUE THREAD

**Issue by minhnguyenwp** [rmrs/react-native-settings#1]
How can i open device settings on iOS?

like AliExpress app. when No internet app will ask user and show dialog, user can click on settings.

**Comment by erezrokah** [comment]
Hello!
Thank your for showing interest in our module.

In iOS there is a public API to open your own app settings using the following url scheme:
Linking.openURL('app-settings:');
See here:
http://stackoverflow.com/questions/39081688/open-settings-app-from-another-app-in-ios-react-native

If you want to open a specific setting there is a private API (which can get your app rejected).
You can read about it here:
https://gist.github.com/phynet/471089a51b8f940f0fb4

While this is a private API, we've noticed it is used by many applications (including google maps), so we are not sure if we should integrate this into our module.

We plan on questioning apple regarding this (and point to the fact that there are very popular apps that must use the private API), since it seems like a trivial issue.

Regards,
Erez

**Comment by minhnguyenwp** [comment]
Thank you for your fast response.

**Comment by erezrokah** [comment]
Closing this issue, please let us know if you have any other questions.

**Comment by dvain** [comment]
Hi erezrokah,

first of all sorry for the thread necromancy but I'm curious: have you ever asked Apple about this? And if so what was there answer? It is kind of an ominous situation. Many devs state their apps have been rejected on using that private API while on the other hand many applications (including Google maps) still use it.
Regards,
dv41n

**Comment by dvain** [comment]
Hey @erezrokah,

thank you for the quick reply. And yeah most use cases seem to be edge cases anyway (depending on the kind of app your developing).

cheers,
dvain
